<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Trajet extends \App\Entity\Trajet implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'dateDepart' => [parent::class, 'dateDepart', null],
        "\0".parent::class."\0".'duree' => [parent::class, 'duree', null],
        "\0".parent::class."\0".'heureDepart' => [parent::class, 'heureDepart', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'placesDisponibles' => [parent::class, 'placesDisponibles', null],
        "\0".parent::class."\0".'reservations' => [parent::class, 'reservations', null],
        "\0".parent::class."\0".'villeArrivee' => [parent::class, 'villeArrivee', null],
        "\0".parent::class."\0".'villeDepart' => [parent::class, 'villeDepart', null],
        'dateDepart' => [parent::class, 'dateDepart', null],
        'duree' => [parent::class, 'duree', null],
        'heureDepart' => [parent::class, 'heureDepart', null],
        'id' => [parent::class, 'id', null],
        'placesDisponibles' => [parent::class, 'placesDisponibles', null],
        'reservations' => [parent::class, 'reservations', null],
        'villeArrivee' => [parent::class, 'villeArrivee', null],
        'villeDepart' => [parent::class, 'villeDepart', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
