<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXQcNRPw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXQcNRPw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXQcNRPw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXQcNRPw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXQcNRPw\App_KernelDevDebugContainer([
    'container.build_hash' => 'XQcNRPw',
    'container.build_id' => '48092282',
    'container.build_time' => 1733275456,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXQcNRPw');
