<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3O872Mn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3O872Mn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3O872Mn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3O872Mn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3O872Mn\App_KernelDevDebugContainer([
    'container.build_hash' => '3O872Mn',
    'container.build_id' => '0bd880eb',
    'container.build_time' => 1732445071,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container3O872Mn');
